### ISSUE TITLE
something goes wrong when I use command line "pip install stacked_generalization"

### ISSUE THREAD

**Issue by wEEang763162** [fukatani/stacked_generalization#6]
here is the detail.
pip install stacked_generalization
Collecting stacked_generalization
  Using cached https://files.pythonhosted.org/packages/d0/99/e42d99355f00068aa2f8eef5f88c1610558f10217e2704067b5134629397/stacked_generalization-0.0.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mm6gy5sl/stacked-generalization/setup.py", line 28, in <module>
        long_description=read_md('Readme.md'),
      File "/tmp/pip-build-mm6gy5sl/stacked-generalization/setup.py", line 13, in <lambda>
        read_md = lambda f: pypandoc.convert(f, 'rst')
      File "/home/wxk/anaconda3/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mm6gy5sl/stacked-generalization/
### Please tell me how to fix it if you know it.

**Comment by fukatani** [comment]
Thank you for your report!
I found pip upload is broken.

You can instgall ny as follows
```
git clone https://github.com/fukatani/stacked_generalization.git
cd stacked_generalization
python setup.py install
```

**Comment by wEEang763162** [comment]
Thank you sincerely.
