### ISSUE TITLE
Scikit-learn version?

### ISSUE THREAD

**Issue by bkj** [fukatani/stacked_generalization#7]
Any idea what the sklearn version here is?  Understand it's a little old, but would like to test the algorithm.  Thanks!

**Comment by fukatani** [comment]
Thank you for sending issue.
Currently, we are fixing stacked_generalization to use with latest scikit-learn.

https://github.com/fukatani/stacked_generalization/pull/8

**Comment by fukatani** [comment]
Resolved by #9
